config/routes.rb
BlogEngine::Engine.routes.draw do
  resources :articles do
    collection do
      put :publish
    end
  end
  get '/admin', to: "admin#index"
  root to: "articles#index"
end

app/models/blog_engine/article.rb
module BlogEngine
  class Article < ActiveRecord::Base
    scope :published,   -> { where(published: true) }
    scope :unpublished, -> { where(published: false) }
    
    VALID_TITLE_REGEX = /\A[a-zA-Z\s\d]+\z/i

    validates :title,
              presence: true,
              format: { with: VALID_TITLE_REGEX },
              uniqueness: { case_sensitive: false },
              length: { maximum: 55, minimum: 6 }

    validates_presence_of :content
    
    before_create :create_permalink
    
    
    def to_param
      permalink
    end
    
    private

    	def create_permalink
    	  count = Article.find_by_sql("SELECT COUNT(*) FROM blog_engine_articles WHERE title = '#{self.title}';")
    	  count = count[0]['count'].to_i
    	  if count > 0
    	    permalink = "#{self.title.gsub(/[^a-z0-9]+/i, '-')}-#{count + 1}".downcase
    	  else
    	  	permalink = "#{self.title.gsub(/[^a-z0-9]+/i, '-')}".downcase
    	  end
    	  self.permalink = permalink
    	end
  end
end

app/models/blog_engine/comment.rb
module BlogEngine
  class Comment < ActiveRecord::Base
    #using disqus for comments
  end
end

app/controllers/blog_engine/admin_controller.rb
require_dependency "blog_engine/application_controller"

module BlogEngine
  class AdminController < ApplicationController
    before_filter :authenticate_user
    
    def index
      @articles = Article.unpublished
    end
    
  end
end

app/controllers/blog_engine/application_controller.rb
class BlogEngine::ApplicationController < ApplicationController
  layout 'layouts/application'
  
  private  
    def authenticate_user
      redirect_to ('/signin') unless current_user
    end 
end

app/controllers/blog_engine/articles_controller.rb
require_dependency "blog_engine/application_controller"

module BlogEngine
  class ArticlesController < ApplicationController
    before_filter :authenticate_user, except: [:index, :show]
    
    def index
      @articles = Article.published.order("created_at DESC").page(params[:page]).per(5)
    end
    
    def show
      @article = Article.find_by_permalink!(params[:id])
      unless @article.published == true
      	redirect_to('/blog/articles')
      end
    end

    def new
      @article = Article.new
    end
    
    def create
      @article = Article.create(article_params)
      @article.user_id = current_user.id
      if @article.save
        redirect_to(@article, notice: "Article has been saved")
      else
        render action: "new"
      end
    end
    
    def edit
      @article = Article.find_by_permalink!(params[:id])
    end
    
    def update
      @article = Article.create(article_params)
      if @article.save
        redirect_to(@article, notice: "Article has been saved")
      else
        render action: "edit"
      end
    end
    
    def publish
      Article.update_all({published: true}, {id: params[:article_ids]})
      redirect_to(admin_path, notice: "Published")
    end
    
    def destroy
      @article = Article.find_by_permalink!(params[:id])
      @article.destroy
      redirect_to(articles_path, notice: "Article was deleted")
    end
    
    private
    
      def article_params
        params.require(:article).permit(:title, :content, :published, :summary, :permalink)
      end
  end
end

app/controllers/blog_engine/comments_controller.rb
require_dependency "blog_engine/application_controller"

module BlogEngine
  class CommentsController < ApplicationController
    before_filter :authenticate_user!
    
    def show
    end

    def create
      @article = BlogEngine::Article.find_by_permalink!(params[:article_id])
      @comment = @article.comments.build(comment_params)
      
      if @comment.save
        redirect_to(@article, notice: "Your comment has been created")
      else
        render 'articles/show', notice: "Please correct the errors and try again"
      end
    end
    
    private
    
    def comment_params
      params.require(:comment).permit(:content, :article_id)
    end
  end
end

app/helpers/blog_engine/application_helper.rb
module BlogEngine
  module ApplicationHelper
    def coderay(text)
      Coderay.scan(text, :ruby).div(:line_numbers => :table)
    end
  end
end

app/helpers/blog_engine/articles_helper.rb
module BlogEngine
  module ArticlesHelper
  end
end

app/helpers/blog_engine/comments_helper.rb
module BlogEngine
  module CommentsHelper
  end
end

app/views/blog_engine/admin/index.html.erb
<h1>Admin Page</h1>
<%= form_tag publish_articles_path, method: :put do %>
	<table>
		<tr>
			<th>Published</th>
			<th>Title</th>
		</tr>
		<% @articles.each do |article| %>
			<tr class="unpublished-article">
				<td><%= check_box_tag "article_ids[]", article.id, false, class: "publish"  %></td>
				<td><%= article.title %></td>
			</tr>
	  <% end %>
	</table>
	<%= submit_tag "Publish Articles" %>
<% end %>

app/views/blog_engine/articles/_article.html.erb
<h1><%= link_to "#{article.title}", article %></h1>
<p><%= article.content.truncate(500).html_safe %></p>
<div>
  <span class="badge">Posted <%= article.created_at.strftime("%B %d, %Y") %></span>

</div>

app/views/blog_engine/articles/_form.html.erb
<%= form_for [blog_engine, @article] do |f| %>
  <div class="wel">
		<div class="field">
			<%= f.label :title %><br/>
			<%= f.text_field :title %>
		</div>
	
		<div class="field">
			<%= f.label :summary %><br/>
			<%= f.text_area :summary %>
		</div>
	
		<div class="field">
			<%= f.label :content %><br/>
			<%= f.text_area :content, class: "wysihtml5" %>
		</div>
	
		<div class="field">
			<%= f.label :published %>
			<%= f.check_box :published %>
		</div>
	
		<div class="actions">
		  <%= f.submit 'Save', class: "btn btn-large btn-primary" %>
		</div>
	</div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5({
			  "html": true,
			});
    });
  })
</script>

app/views/blog_engine/articles/edit.html.erb
<%= render 'form' %>

app/views/blog_engine/articles/index.html.erb
<%= render @articles %>
<% if current_user %>
  <%= link_to 'New Article', blog_engine.new_article_path %>
<% end %>
 
<%= paginate @articles %>

app/views/blog_engine/articles/new.html.erb
<%= render 'form' %>

app/views/blog_engine/articles/show.html.erb
<div class="article">
	<% if current_user %>
	  <%=link_to "Edit", blog_engine.edit_article_path(@article) %>
	<% end %>
	<h1><%= @article.title%></h1>

	
	<%= raw Pygments.highlight(@article.content, lexer: "ruby") %>
	
</div>
	
<div class="comments">	
	<%= render :partial => "shared/disqus", :locals => { title: @article.title } %>
</div>

app/views/blog_engine/comments/_comment.html.erb
<div class="comment">
  <%= comment.content %>
</div>

app/views/blog_engine/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/blog_engine/comments/create.html.erb</p>

app/views/blog_engine/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/blog_engine/comments/show.html.erb</p>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'roberthuberdeau'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>